"""add original_filename to documents

Revision ID: acac6ed88ed8
Revises: 2548fdf5cfef
Create Date: 2026-04-21 09:29:06.376747

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "acac6ed88ed8"
down_revision: Union[str, Sequence[str], None] = "2548fdf5cfef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("chunks_embedding_hnsw_idx"),
        table_name="chunks",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="hnsw",
    )
    op.add_column(
        "documents", sa.Column("original_filename", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "original_filename")
    op.create_index(
        op.f("chunks_embedding_hnsw_idx"),
        "chunks",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="hnsw",
    )
    # ### end Alembic commands ###
